### PR TITLE
Upgrade to 1.5.11

### PR DESCRIPTION
**Pull request by anto1ne**
This is an update of fluxbb_ynh : 
 * it should now be working 
 * an reach level 3

### CODE REVIEW

**Comment by frju365** [comment]
mh... Why use AGPL instead of GPL ? I prefer GPL. :/

**Comment by anto1ne** [comment]
well, I am not a license expert ..
I chose AGPL because 
 * it is the one used by yunohost, 
 * it is the one recommended by the Free Software Fondation (FSF) for application that can be run over a network (https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)

what bothers you in this license ?

**Comment by anto1ne** [comment]
I checked fluxbb_ynh with package_check, everything look ok


```
Stop the LXC container
Restore the previous snapshot.
Working time: 9 seconds.
Restore the previous snapshot.
Working time: 1 second.
Working time for this test: 2 minutes, 27 seconds.
Package linter: SUCCESS
Installation: SUCCESS
Deleting: SUCCESS
Installation in a sub path: SUCCESS
Deleting from a sub path: SUCCESS
Installation on the root: SUCCESS
Deleting from root: SUCCESS
Upgrade: SUCCESS
Installation in private mode: SUCCESS
Installation in public mode: SUCCESS
Multi-instance installations: SUCCESS
Malformed path: SUCCESS
Port already used: Not evaluated.
Backup: SUCCESS
Restore: SUCCESS
Change URL: SUCCESS
Level of this application: 7 ()
	   Level 1: 1
	   Level 2: 1
	   Level 3: 1
	   Level 4: 1
	   Level 5: 1
	   Level 6: 1
	   Level 7: 1
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
Global working time for all tests: 19 minutes, 45 seconds.
```

**Comment by frju365** [comment]
Ok. I approve. For license, it's ok (after some research).

**Review by frju365 — APPROVED** [review]

**Pull request merged**
